ALTER TABLE aca_faculty
ADD FOREIGN KEY (AYCode) REFERENCES academic_year(AYCode) ON UPDATE CASCADE ON DELETE RESTRICT,
ADD FOREIGN KEY (FCode) REFERENCES faculty(FCode) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE aca_fac_pro
ADD FOREIGN KEY (AFCode) REFERENCES aca_faculty(AFCode) ON UPDATE CASCADE ON DELETE RESTRICT,
ADD FOREIGN KEY (PCode) REFERENCES program(PCode) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE aca_pro_mod
ADD FOREIGN KEY (PFCode) REFERENCES aca_fac_pro(PFCode) ON UPDATE CASCADE ON DELETE RESTRICT,
ADD FOREIGN KEY (MCode) REFERENCES module(MCode) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE Semester
ADD FOREIGN KEY (AYCode) REFERENCES Academic_Year(AYCode) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE Class
ADD FOREIGN KEY (SCode) REFERENCES Semester(SCode) ON UPDATE CASCADE ON DELETE RESTRICT,
ADD FOREIGN KEY (MCode) REFERENCES Module(MCode) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE Lecturer
ADD FOREIGN KEY (CCode) REFERENCES Class(CCode) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE questionnaire
DROP CONSTRAINT questionnaire_ibfk_2,
ADD FOREIGN KEY (LCode) REFERENCES Lecturer(LCode) ON UPDATE CASCADE ON DELETE RESTRICT;
